export const siteConfig = {
  siteUrl: "https://prnit.com",
  organizationName: "PRNIT",
  legalName: "Prnit India LLP",
  founderName: "Praveen Singh Shekhawat",
  founderLinkedIn: "https://www.linkedin.com/in/praveenshekhawat/",
  founderToptal: "https://www.toptal.com/developers/resume/praveen-singh-shekhawat",
  foundingDate: "2011-01",
  companyType: "Technology company — software development & engineering consulting",
  primaryLocation: "Jaipur, India",
  secondaryLocation: "Bangkok, Thailand",
  headquartersAddressLine1: "24-A, Umraw Vihar, Gokulpura, Jhotwara",
  headquartersCity: "Jaipur",
  headquartersPostalCode: "302012",
  headquartersCountryCode: "IN",
  email: "hello@prnit.com",
  phone: "+91 97853 94461",
  phoneE164: "+919785394461",
  socialProfiles: [
    "https://www.facebook.com/prnitsoftware",
    "https://www.instagram.com/prnitsoftware",
    "https://www.twitter.com/prnitsoftware",
    "https://www.linkedin.com/company/prnitsoftware",
    "https://www.dribbble.com/prnitsoftware",
  ],
  founderSocialProfiles: [
    "https://www.linkedin.com/in/praveenshekhawat/",
    "https://www.toptal.com/developers/resume/praveen-singh-shekhawat",
  ],
  teamExperienceRange: "8-14 years",
  industriesCount: 8,
  weeklyTimeSaved: "30-40 hrs/week",
  yearsInBusiness: "14+",
  projectsCount: "TBD (replace with verified total)",
} as const;
